import { Link, useNavigate } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { getServices } from "@/features/services/api";
import { useAuth } from "@/hooks/useAuth";
import { useServiceSelectionStore } from "@/store/serviceSelectionStore";
import type { Service } from "@/types/service";
const categories = ["All", "Manicure", "Pedicure", "NailArt", "AddOn", "Other"];
export default function ServicesPage() {
 const { isAuthenticated } = useAuth(); const navigate = useNavigate(); const [category,setCategory]=useState("All"); const [search,setSearch]=useState(""); const [items,setItems]=useState<Service[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const {items:selected,toggle}=useServiceSelectionStore();
 useEffect(()=>{ setLoading(true); getServices({ category: category === "All" ? undefined : category, search, pageSize: 50 }).then(x=>setItems(x.items)).catch(()=>setError(true)).finally(()=>setLoading(false)); },[category,search]);
 const totals=useMemo(()=>selected.reduce((x,s)=>({price:x.price+s.price,duration:x.duration+s.durationMinutes}),{price:0,duration:0}),[selected]);
 return <main className="min-h-screen bg-[#f8fbff] text-slate-900"><header className="flex items-center justify-between border-b bg-white px-6 py-5"><Link className="text-2xl font-extrabold text-blue-600 no-underline" to="/">Nailify</Link><nav className="flex gap-5 text-sm"><Link to="/">Home</Link><Link className="font-bold text-blue-600" to="/services">Services</Link><Link to="/nail-designs">Nail Designs</Link></nav>{isAuthenticated?<span className="text-sm font-semibold">Customer</span>:<div className="flex gap-2"><Link className="px-3 py-2 text-sm" to="/login">Log in</Link><Link className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white" to="/register">Sign up</Link></div>}</header><div className="mx-auto max-w-7xl px-6 py-10"><h1 className="text-4xl font-extrabold">Nail services</h1><p className="mt-2 text-slate-500">Choose one or more services before selecting an appointment time.</p><div className="mt-7 flex flex-wrap gap-2">{categories.map(x=><button className={`rounded-full border px-4 py-2 text-sm ${category===x?"bg-blue-600 text-white":"bg-white"}`} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><input className="mt-5 w-full max-w-xl rounded-xl border p-3" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search services" />{loading?<p className="py-12">Loading services…</p>:error?<p className="py-12 text-red-700">Unable to load services. Please try again.</p>:<div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(s=><article className="rounded-2xl border bg-white p-5 shadow-sm" key={s.id}>{s.imageUrl?<img className="mb-4 h-40 w-full rounded-xl object-cover" src={s.imageUrl} onError={(e)=>{e.currentTarget.style.display="none";}} alt=""/>:<div className="mb-4 grid h-40 place-items-center rounded-xl bg-blue-50 text-4xl text-blue-500">✦</div>}<span className="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-700">{s.category}</span><h2 className="mt-3 text-lg font-bold">{s.name}</h2><p className="mt-1 min-h-10 text-sm text-slate-500">{s.description || "Professional nail salon service."}</p><p className="mt-4 font-semibold">${s.price} · {s.durationMinutes} min</p><button disabled={!isAuthenticated} onClick={()=>toggle(s)} className="mt-4 w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:cursor-not-allowed disabled:bg-slate-300">{!isAuthenticated?"Sign in to book":selected.some(x=>x.id===s.id)?"Remove from booking":"Add to booking"}</button></article>)}</div>}{isAuthenticated&&selected.length>0&&<aside className="fixed bottom-5 right-5 rounded-2xl bg-slate-900 p-5 text-white shadow-xl"><strong>{selected.length} service{selected.length>1?"s":""} selected</strong><p className="mt-1 text-sm">${totals.price} · {totals.duration} min</p><button onClick={()=>navigate("/booking")} className="mt-3 rounded-lg bg-white px-4 py-2 text-sm font-bold text-slate-900">Continue to booking</button></aside>}</div></main>;
}
